---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
CSV_for_ConditionsStandardConditions_YeastStrainWildType_Plate_24423 <- read_csv("~/repo/CurveAnalysis/CSVFiles/CSV_for_ConditionsStandardConditions,YeastStrainWildType_Plate_24423.csv")
current.data<-CSV_for_ConditionsStandardConditions_YeastStrainWildType_Plate_24423
current.data[grep("X",names(current.data))]<-NULL
current.data
log.od<-log(t(as.matrix(current.data[,-1])))
matplot(log.od,type="l")
dim(log.od)
time<-as.numeric(colnames(current.data[-1]))
rates<-apply(log.od,MARGIN = 2,FUN=function(x)diff(x)/diff(time))
matplot(rates,type="l")
plot(rowMeans(rates),type="l")
abline(h=0)
current.data<-as.data.frame(current.data)
colnames(current.data[,-1])<-1:130
#reshape data for lmer
tmp2<-reshape(data=current.data,direction = "long",varying=colnames(current.data[,-1]),v.names ="OD" ,timevar = "Time",times =time)
#Wrapper for Mixed effects model with variable break point
foo <- function(bp)
{
  mod <- lmer(LogOD ~ b1(Time, bp) + b2(Time, bp) + (b1(Time, bp) + b2(Time, bp) | Well), data = tmp2)
  deviance(mod,REML=FALSE)
}


N <- 40 # number of sampled points
K <- 3  # number of knots

piece.formula <- function(var.name, knots) {
  formula.sign <- rep(" - ", length(knots))
  formula.sign[knots < 0] <- " + "
  paste(var.name, "+",
        paste("I(pmax(", var.name, formula.sign, abs(knots), ", 0))",
              collapse = " + ", sep=""))
}
library(lme4)
library(bcp)
plot(bcp(log.od))
knots<-time[c(20,50,100)]
#model <- lmer(formula=formula(paste("log(OD) ~",paste( piece.formula("Time", knots),"+1|Well_Name"))),data = tmp2 )
 rand.slope<-paste("(1+",paste(piece.formula("Time", knots),")|Well_Name"))
model <- lmer(formula=formula(paste("log(OD) ~1+",rand.slope)),data = tmp2 )
```

No with stan

```{r}

#time[1]=0
#OD<-as.matrix(current.data[,-1])
M <- ceiling(length(time)^(2/3))
#M<-10
N <- 16
K=2
#OD<-as.matrix(current.data[1:N,-1])
T<- length(time)


#timeN<--1*normalize.interval(time)

OD.old<-OD
```

```{r}
library(rstan)
library(coda)
library(ggmcmc)
library(bcp)
set.seed(123)
P=16;
N=16;
#prior<-matrix(,N,P)
p<- bcp(t(OD))
prior<-which(p$posterior.prob>0.8)
prior<-prior
#prior<-c(20,39)
P<-length(prior)

#for(i in 1:N){
#  p<- bcp(OD[i,],time)
#  temp<-order(p$posterior.prob,decreasing = T)
  #temp<-temp[temp>18]

# prior[i,]<-sort(temp[1:P])
#}
#p<-bcp(t(OD))
#prior<-which(p$posterior.prob>0.5)
#prior<-c(17,39)
#prior<-c(10:16,prior[2:length(prior)])
#prior<-c(26,41)
#prior<-c(1:26,prior[3:length(prior)])
#P<-length(prior)
M=80
MAXT=max(time)
X<-bernstein.matrix(M,time,a=time[1],b=time[length(time)])
D<-bernstein.derivative.operator(M)
subdiv<-0.5
#timeN[1]<-1e-6

L<-which(timeN<=subdiv)
L<-L[length(L)]
#Q<-subdivision.matrix(timeN[L],M)
Xs<-bernstein.matrix(M,time[1:L],a=time[1],b=time[L])
Xa<-bernstein.matrix(M,time[L:T],a=time[L],b=time[length(time)])
#Id<-bernstein.integral.operator(M)
OD<-OD.old[1:N,]
#OD<-t(scale(t(OD)))
#MIN=min(log(OD))
#MAX=max(log(OD))
MIN=0
MAX=max(OD)+0.1
#LAMBDA=20
#SIGMA_MU=0.01
SIGMA_MU=0.01
K0=0.01
#MU=c(0.2,0.06)
MU=c(0,0.3,0)
LAMBDA=1
SIGMA_A=0.1
#timeN <- as.numeric(colnames(OD.old))
#timeN[1] <- 0
#timeN<--1*normalize.interval(timeN)
T <- length(timeN)
#model <- stan_model(file = "BernsteinFitLOG.stan")
model <- stan_model(file = "BernsteinFitPooled.stan")
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
fit<-vb(model)

#fit<-stan("BernsteinFitDynamic.stan",chains=2, seed=123)

#fit<-stan("CurveAnalysis.stan",chains = 3)
save(list="fit",file="fit.RData")
#fitrstan::optimizing()
s <- mcmc.list(lapply(1:ncol(fit), function(x) mcmc(as.array(fit)[,x,])))

S <- ggs(s)

#ggs_caterpillar(S,family = "rate")
ggs_caterpillar(S,family = "sigma")
ggs_caterpillar(S,family="MU")
ggs_caterpillar(S,family="lambda")
#gs_caterpillar(S,family="intercept")
#ggs_geweke(S)
ggs_caterpillar(S,family = "DA_coef")
ggs_caterpillar(S,family = "^A_coef")
<<<<<<< HEAD
ggs_histogram(S,family = "tau")
=======
ggs_histogram(S,family="tau")
>>>>>>> 2f90e317b71bd6750f2b159f4a54b2b4b53f0f50
#ggs_caterpillar(S,family = "lp")
#ggs_caterpillar(S,family="intercept")

#plotfit(fit)
#save(list="fit",file="fitADVI.RData")
#matplot(t(OD),type="l")
#tmp<-rstan::extract(fit,"rate")
#rate<-tmp$rate

#t2<-t(matrix(colMeans(rate),N,3))
#boxplot(t(t2),type="l")

tmp<-rstan::extract(fit,"OD_pred")
ODp<-tmp$OD_pred
plot(colMeans(ODp))
#ODp<-t(matrix(colMeans(ODp),N,T))
#matplot(ODp,type="l")
#matplot(t(OD),type="l",ylim=c(0,0.9))

tmp<-rstan::extract(fit,"DOD_pred")
DODp<-tmp$DOD_pred
plot(colMeans(DODp))
#plot(colMeans(DODp)/colMeans(ODp))
#DODp<-t(matrix(colMeans(DODp),N,T))
#matplot((1/MAXT)*DODp,type="l")
#matplot(DODp/ODp,type="l",main="loss posterior")

tmp<-rstan::extract(fit,"loss")
lossp<-tmp$loss
plot(colMeans(lossp))
#lossp<-t(matrix(colMeans(lossp),N,T))
#matplot(lossp,type="l",title="loss")
abline(h=0)

tmp<-rstan::extract(fit,"curve")
curvep<-tmp$curve
plot(colMeans(curvep),type="l")
lines(colMeans((OD)))
#lossp<-t(matrix(colMeans(log(curvep)),N,T))
#matplot(lossp,type="l",title="loss")
abline(h=0)

tmp<-rstan::extract(fit,"lp")
lpp<-tmp$lp
lpp<- matrix(colMeans(lpp),P,P)
library(gplots)
heatmap(lpp,Rowv = NA,Colv=NA)
#lines(diff(ODp[,2]/diff(timeN)))

#plot(diff(ODp[,2]/(65*diff(timeN))))
#plot(diff(OD[2,])/diff(time))

#matplot(t(log(OD))-MIN,type="l")
plot(bcp(lossp))
tmp<-rstan::extract(fit,"logCurve")
logcurvep<-tmp$logCurve
plot(colMeans(logcurvep))

#lossp<-t(matrix(colMeans(curvep),N,T))
#matplot(lossp,type="l",title="loss")
abline(h=0)
#rate<-(matrix(colMeans(rate),N,2))
#boxplot(rate,main="mean rates")
#plot(colMeans(rate[,1,1]))
```



```{r}
library(readr)
#SV <- read_csv("~/repo/CurveAnalysis/CSVFiles/CSV_for_ConditionsStandardConditions,YeastStrainYAL051W_Plate_24423.csv")
#current.data<-SV
#current.data[grep("X",names(current.data))]<-NULL
#current.data
#OD.old<-as.matrix(current.data[,-1])
set.seed(123)
P=16;
N=16;
#prior<-matrix(,N,P)
p<- bcp(t(OD))
prior<-which(p$posterior.prob>0.2)
prior<-prior
#prior<-c(20,39)
P<-length(prior)

#for(i in 1:N){
#  p<- bcp(OD[i,],time)
#  temp<-order(p$posterior.prob,decreasing = T)
  #temp<-temp[temp>18]

# prior[i,]<-sort(temp[1:P])
#}
#p<-bcp(t(OD))
#prior<-which(p$posterior.prob>0.5)
#prior<-c(17,39)
#prior<-c(10:16,prior[2:length(prior)])
#prior<-c(26,41)
#prior<-c(1:26,prior[3:length(prior)])
#P<-length(prior)
M=26
MAXT=max(time)
X<-bernstein.matrix(M,time,a=time[1],b=time[length(time)])
D<-bernstein.derivative.operator(M)
subdiv<-0.5
#timeN[1]<-1e-6

L<-which(timeN<=subdiv)
L<-L[length(L)]
#Q<-subdivision.matrix(timeN[L],M)
Xs<-bernstein.matrix(M,time[1:L],a=time[1],b=time[L])
Xa<-bernstein.matrix(M,time[L:T],a=time[L],b=time[length(time)])
#Id<-bernstein.integral.operator(M)
OD<-OD.old[1:N,]
K=6
#OD<-t(scale(t(OD)))
#MIN=min(log(OD))
#MAX=max(log(OD))
MIN=0
MAX=max(OD)+0.1
#LAMBDA=20
#SIGMA_MU=0.01
SIGMA_MU=.01
K0=0.01
#MU=c(0.2,0.06)
MU=c(0,0.2,0.06)
LAMBDA=1
SIGMA_A=0.1
SIGMA_U=0.01
#timeN <- as.numeric(colnames(OD.old))
#timeN[1] <- 0
#timeN<--1*normalize.interval(timeN)
T <- length(timeN)
#model <- stan_model(file = "BernsteinFitLOG.stan")
model <- stan_model(file = "BernsteinFitPooled.stan")
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
fit<-vb(model)

#fit<-stan("BernsteinFitDynamic.stan",chains=2, seed=123)
#save(list="fit",file="fit.RData")
#fit<-stan("CurveAnalysis.stan",chains = 2)
#fitrstan::optimizing()
s <- mcmc.list(lapply(1:ncol(fit), function(x) mcmc(as.array(fit)[,x,])))

S <- ggs(s)

#ggs_caterpillar(S,family = "rate")
ggs_caterpillar(S,family = "sigma")
ggs_caterpillar(S,family="MU")
ggs_caterpillar(S,family="lambda")
#gs_caterpillar(S,family="intercept")
#ggs_geweke(S)
ggs_caterpillar(S,family = "DA_coef")
ggs_caterpillar(S,family = "^A_coef")
ggs_histogram(S,family="tau")
#ggs_caterpillar(S,family = "lp")
#ggs_caterpillar(S,family="intercept")

#plotfit(fit)
#save(list="fit",file="fitADVI.RData")
#matplot(t(OD),type="l")
#tmp<-rstan::extract(fit,"rate")
#rate<-tmp$rate

#t2<-t(matrix(colMeans(rate),N,3))
#boxplot(t(t2),type="l")

tmp<-rstan::extract(fit,"OD_pred")
ODp<-tmp$OD_pred
#plot(colMeans(ODp))
ODp<-t(matrix(colMeans(ODp),K,T))
matplot(ODp,type="l")

tmp<-rstan::extract(fit,"DOD_pred")
DODp<-tmp$DOD_pred
DODp<-t(matrix(colMeans(DODp),K,T))
matplot(DODp,type="l")

tmp<-rstan::extract(fit,"loss")
lossp<-tmp$loss
plot(colMeans(lossp))
lossp<-t(matrix(colMeans(lossp),K,T))
matplot(lossp,type="l",title="loss")
abline(h=0)

tmp<-rstan::extract(fit,"curve")
curvep<-tmp$curve
curvep<-t(matrix(colMeans((curvep)),K,T))
matplot(curvep,type="l",title="loss")
abline(h=0)

#tmp<-rstan::extract(fit,"lp")
#lpp<-tmp$lp
#lpp<- matrix(colMeans(lpp),P,P)
#library(gplots)
#heatmap(lpp,Rowv = NA,Colv=NA)
#lines(diff(ODp[,2]/diff(timeN)))

#plot(diff(ODp[,2]/(65*diff(timeN))))
#plot(diff(OD[2,])/diff(time))

#matplot(t(log(OD))-MIN,type="l")
plot(bcp(lossp))
tmp<-rstan::extract(fit,"logCurve")
logcurvep<-tmp$logCurve
#plot(colMeans(logcurvep))
logCurvep<-t(matrix(colMeans(logcurvep),K,T))
#matplot(lossp,type="l",title="loss")
abline(h=0)
ggs_caterpillar(S,family = "theta")
#rate<-(matrix(colMeans(rate),N,2))
#boxplot(rate,main="mean rates")
#plot(colMeans(rate[,1,1]))
```

```{r}
library(readr)
SV <- read_csv("~/repo/curveanalysis/CSVFiles/CSV_for_ConditionsStandardConditions,YeastStrainYPL230W_Plate_24429.csv")
SV2 <- read_csv("~/repo/curveanalysis/CSVFiles/CSV_for_ConditionsStandardConditions,YeastStrainYPL230W_Plate_24426.csv")
SV3 <- read_csv("~/repo/curveanalysis/CSVFiles/CSV_for_ConditionsStandardConditions,YeastStrainYPL230W_Plate_24430.csv")
SV4 <- read_csv("~/repo/curveanalysis/CSVFiles/CSV_for_ConditionsStandardConditions,YeastStrainYPL230W_Plate_24428.csv")
current.data<-SV
current.data[grep("X",names(current.data))]<-NULL
current.data
OD.old<-as.matrix(current.data[,-1])

current.data<-SV2
current.data[grep("X",names(current.data))]<-NULL
current.data
OD.old<-rbind(OD.old,as.matrix(current.data[,-1]))

#current.data<-SV3
#current.data[grep("X",names(current.data))]<-NULL
#current.data
#OD<-rbind(OD.old,as.matrix(current.data[,-1]))


current.data<-SV4
current.data[grep("X",names(current.data))]<-NULL
current.data
OD<-rbind(OD.old,as.matrix(current.data[,-1]))
set.seed(123)
P=16;
N=nrow(OD);
PL=3;
pl=c(rep(1,4),rep(2,4),rep(3,4))
time=as.numeric(colnames(OD))
T=length(time)
timeN=normalize.interval(time)
#prior<-matrix(,N,P)
p<- bcp(t(OD))
prior<-which(p$posterior.prob>0.2)
LAGT<-prior[1]
#prior<-prior[2:length(prior)]
#prior<-c(1,prior)
#prior<-c(20,39)
P<-length(prior)

#for(i in 1:N){
#  p<- bcp(OD[i,],time)
#  temp<-order(p$posterior.prob,decreasing = T)
  #temp<-temp[temp>18]

# prior[i,]<-sort(temp[1:P])
#}
#p<-bcp(t(OD))
#prior<-which(p$posterior.prob>0.5)
#prior<-c(17,39)
#prior<-c(10:16,prior[2:length(prior)])
#prior<-c(26,41)
#prior<-c(1:26,prior[3:length(prior)])
#P<-length(prior)
M=50
MAXT=max(time)
X<-bernstein.matrix(M,time,a=time[1],b=time[length(time)])
XD<-bernstein.basis.derivative.matrix(m = M,time = timeN)
D<-bernstein.derivative.operator(M)
subdiv<-0.5
#timeN[1]<-1e-6

L<-which(timeN<=subdiv)
L<-L[length(L)]
#Q<-subdivision.matrix(timeN[L],M)
Xs<-bernstein.matrix(M,time[1:L],a=time[1],b=time[L])
Xa<-bernstein.matrix(M,time[L:T],a=time[L],b=time[length(time)])
#Id<-bernstein.integral.operator(M)
#OD<-OD.old[1:N,]
K=6
#OD<-t(scale(t(OD)))
#MIN=min(log(OD))
#MAX=max(log(OD))
MIN=0
MAX=max(OD)+0.1
#LAMBDA=20
#SIGMA_MU=0.01
SIGMA_MU=.01
K0=0.01
#MU=c(0.2,0.06)
MU=c(0,0.2,0.06)
LAMBDA=1
SIGMA_A=0.1
SIGMA_U=0.01
#timeN <- as.numeric(colnames(OD.old))
#timeN[1] <- 0
#timeN<--1*normalize.interval(timeN)
#T <- length(timeN)
#model <- stan_model(file = "BernsteinFitLOG.stan")
model1B <- stan_model(file = "HierarchicalEffect1BP.stan")
model2B <- stan_model(file = "HierarchicalEffect2BP.stan")
model3B <- stan_model(file = "HierarchicalEffect3BP.stan")
model4B <- stan_model(file = "HierarchicalEffect4BP.stan")
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
fit<-vb(model1B)

#fit<-sampling(model1BP,warmup=10000,iter=11000,chains = 4)
#save(list="fit",file="fit.RData")

#fitrstan::optimizing()
s <- mcmc.list(lapply(1:ncol(fit), function(x) mcmc(as.array(fit)[,x,])))

S <- ggs(s)

#ggs_caterpillar(S,family = "rate")
ggs_caterpillar(S,family = "sigma")
ggs_caterpillar(S,family="MU")
ggs_caterpillar(S,family="lambda")
#gs_caterpillar(S,family="intercept")
#ggs_geweke(S)
ggs_caterpillar(S,family = "DA_coef")
ggs_caterpillar(S,family = "^A_coef")
ggs_histogram(S,family="tau")
#ggs_caterpillar(S,family = "lp")
#ggs_caterpillar(S,family="intercept")

#plotfit(fit)
#save(list="fit",file="fitADVI.RData")
#matplot(t(OD),type="l")
#tmp<-rstan::extract(fit,"rate")
#rate<-tmp$rate

#t2<-t(matrix(colMeans(rate),N,3))
#boxplot(t(t2),type="l")

tmp<-rstan::extract(fit,"OD_pred")
ODp<-tmp$OD_pred
#plot(colMeans(ODp))
#ODp<-t(matrix(colMeans(ODp),K,T))
plot(colMeans(ODp),type="l")

tmp<-rstan::extract(fit,"DOD_pred")
DODp<-tmp$DOD_pred

plot(colMeans(DODp),type="l")

tmp<-rstan::extract(fit,"loss")
lossp<-tmp$loss
plot(colMeans(lossp))
#lossp<-t(matrix(colMeans(lossp),K,T))
#plot(lossp,type="l",title="loss")
abline(h=0)

tmp<-rstan::extract(fit,"curve")
curvep<-tmp$curve
plot(colMeans(curvep))
lines(colMeans(OD))
#curvep<-t(matrix(colMeans((curvep)),K,T))
#matplot(curvep,type="l",title="loss")
abline(h=0)


tmp<-rstan::extract(fit,"piece_pred")
piecep<-tmp$piece_pred
plot(colMeans(piecep),type="l")
lines(colMeans(OD))
#curvep<-t(matrix(colMeans((curvep)),K,T))
#matplot(curvep,type="l",title="loss")
abline(h=0)
#tmp<-rstan::extract(fit,"lp")
#lpp<-tmp$lp
#lpp<- matrix(colMeans(lpp),P,P)
#library(gplots)
#heatmap(lpp,Rowv = NA,Colv=NA)
#lines(diff(ODp[,2]/diff(timeN)))

#plot(diff(ODp[,2]/(65*diff(timeN))))
#plot(diff(OD[2,])/diff(time))

#matplot(t(log(OD))-MIN,type="l")
#plot(bcp(lossp))
tmp<-rstan::extract(fit,"logCurve")
logcurvep<-tmp$logCurve
#plot(colMeans(logcurvep))
logCurvep<-t(matrix(colMeans(logcurvep),K,T))
#matplot(lossp,type="l",title="loss")
abline(h=0)
#ggs_caterpillar(S,family = "theta")
ggs_histogram(S,family="V")

ggs_histogram(S,family="s1")
ggs_histogram(S,family="s2")
```


